version: "3.9"

networks:
  yingxue-network:

volumes:
  data:

services:
  nacos:
    image: nacos/nacos-server:2.0.2
    container_name: nacos
    ports:
      - "8848:8848"
    environment:
      - "JVM_XMS=256m"
      - "JVM_XMX=256m"
      - "MODE=standalone"
    networks:
      - yingxue-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - yingxue-network
    volumes:
      - data:/var/lib/mysql
      - ./yingxue.sql:/docker-entrypoint-initdb.d/yingxue.sql
    environment:
      - "MYSQL_ROOT_PASSWORD=heyufeng"
      - "MYSQL_DATABASE=yingxue"