server:
  port: 9999
spring:
  application:
    name: API-GATEWAY
  cloud:
    nacos:
      server-addr: 192.168.108.130:8848

    gateway:
      routes:
        # admins router
        - id: admins_router
          uri: lb://API-ADMINS
          predicates:
            - Path=/admin/demos,/admin/tokens,/admin/admin-user,/admin/tokens/**
          filters:
            - StripPrefix=1
        # category router
        - id: category_router
          uri: lb://API-CATEGORY
          predicates:
            - Path=/admin/categories/**
          filters:
            - StripPrefix=1
        # users router
        - id: users_router
          uri: lb://API-USERS
          predicates:
            - Path=/admin/users/**
          filters:
            - StripPrefix=1
        # videos router
        - id: videos_router
          uri: lb://API-VIDEOS
          predicates:
            - Path=/videos/demos
          filters:
            - StripPrefix=1
      # 跨域配置处理
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"