server:
  port: 8980
spring:
  application:
    name: API-ADMINS
  cloud:
    nacos:
      server-addr: 192.168.108.130:8848

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.108.130:3306/yingxue?characterEncoding=UTF-8&useSSL=false
    username: root
    password: heyufeng

  redis:
    host: 192.168.108.130
    port: 6379


mybatis-plus:
  mapper-locations: classpath:com/shamengxin/mapper/*.xml
  type-aliases-package: com.shamengxin.entity

logging:
  level:
    com.shamengxin.mapper: debug
